name: Build & Push

on:
  push:
    branches:
      - main

env:
  REPOSITORY: temibabs/naija-echos
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build:
    name: Build and push to Dockerhub
    runs-on: ubuntu-latest
    environment: staging

    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build, tag, and push image to Docker Hub
      uses: docker/build-push-action@v3
      id: build-image
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          GIT_TOKEN=${{ secrets.GIT_TOKEN }}
        push: true
        tags: ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }},${{ env.REPOSITORY }}:latest
